name: device_packages
description: Flutter plugin to get android device packages (apps), listen when an app is installed and uninstalled (ACTION_PACKAGE_ADDED and ACTION_PACKAGE_REMOVED).
version: 0.1.0
homepage: https://github.com/alexrintt/device-packages
repository: https://github.com/alexrintt/device-packages
issue_tracker: https://github.com/alexrintt/device-packages
documentation: https://github.com/alexrintt/device-packages
funding:
  - https://www.buymeacoffee.com/alexrintt
  - https://www.github.com/sponsors/alexrintt
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  # Development dependencies:
  device_packages_android:
    path: ../device_packages_android
  device_packages_platform_interface:
    path: ../device_packages_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: device_packages_android
