name: device_packages_android
description: Android implementation of [device_packages] plugin.
version: 0.1.0
homepage: https://github.com/alexrintt/device-packages
repository: https://github.com/alexrintt/device-packages
issue_tracker: https://github.com/alexrintt/device-packages
documentation: https://github.com/alexrintt/device-packages
funding:
  - https://www.buymeacoffee.com/alexrintt
  - https://www.github.com/sponsors/alexrintt

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0

flutter:
  plugin:
    implements: device_packages
    platforms:
      android:
        package: io.alexrintt.device_packages_android
        pluginClass: DevicePackagesAndroidPlugin
